### ISSUE TITLE
BrokenPipeError raised, no data being uploaded to S3

### ISSUE THREAD

**Issue by KCAmplify** [TicketSwap/target-redshift#104]
**Describe the bug**
Data is not loaded in red-shift, issue seems to be failing on
https://github.com/TicketSwap/target-redshift/blob/main/target_redshift/sinks.py#L215
due to the data being extracted.
I can load data fine when using jsonl loader.
When using Redshift loader, I see a csv file under temp folder, but nothing gets uploaded to s3.
I can upload file to s3 manually using aws s3 command within the same console.

**To Reproduce**
1. Set-up extractor to be from HubSpot
2. Set-up loader to be RedShift
3. Run

**Expected behavior**
Redshift should be able to load data without error

**Screenshots**
![image](https://github.com/user-attachments/assets/dc035194-0ab6-4dbf-bb9c-58c07a146197)
![image](https://github.com/user-attachments/assets/193511c2-b6e4-4854-bf22-6254b67d9c0f)
![image](https://github.com/user-attachments/assets/c9970cd0-a186-41e0-a3c5-9594e2a41eb6)
![image](https://github.com/user-attachments/assets/e872041e-d7be-458e-b37b-6d0d4f9fa30a)
![image](https://github.com/user-attachments/assets/59d2d423-646c-4b33-a732-1a06bccee926)
![image](https://github.com/user-attachments/assets/c9bc359f-7d39-4d15-bb07-2ba81abb93d1)

2024-08-06T19:24:15.413077Z [info     ]   File "/home/ec2-user/eval/.meltano/loaders/target-redshift/venv/lib/python3.9/site-packages/target_redshift/sinks.py", line 215, in <dictcomp> cmd_type=elb consumer=True job_name=staging:tap-hubspot-to-target-redshift name=target-redshift producer=False run_id=d7ca55e2-84c2-4ad7-b724-211055c09ea6 stdio=stderr string_id=target-redshift
2024-08-06T19:24:15.413275Z [info     ]     {key: (json.dumps(value).replace("None", "") if key in object_keys else value) for key, value in record.items()} cmd_type=elb consumer=True job_name=staging:tap-hubspot-to-target-redshift name=target-redshift producer=False run_id=d7ca55e2-84c2-4ad7-b724-211055c09ea6 stdio=stderr string_id=target-redshift

{key: (json.dumps(value).replace("None", "") if key in object_keys else value) for key, value in record.items()}

TypeError: Object of type Decimal is not JSON serializable

**Desktop (please complete the following information):**
 - OS: Amazon Linux
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by cfeduke** [comment]
I was helping to troubleshoot this problem on the Meltano Slack. It seems like the problem is that the CSV file is not completed due to an uncaught exception at https://github.com/TicketSwap/target-redshift/blob/c483ee2c32b5e663d754b39330406e8d19132ef0/target_redshift/sinks.py#L215

The message is: `TypeError: Object of type Decimal is not JSON serializable`

It seems like `json.dumps(value, default=str)` _could_ work, or using a custom JSON encoding class to handle the Decimal type.

**Comment by KCAmplify** [comment]
I don't know if this is the correct solution or not, but I've changed
https://github.com/TicketSwap/target-redshift/blob/main/target_redshift/sinks.py#L9
to
`import simplejson as json`
And installed simplejson in my environment, and I was able to get past this issue.

**Comment by tobiascadee** [comment]
@cfeduke this seems like a good suggestion. I will create a PR

**Comment by tobiascadee** [comment]
@KCAmplify let me check if this works!
